### ISSUE TITLE
[BUG] Line of Sight

### ISSUE THREAD

**Issue by sluwe-vos** [CalderCob/EOA-bug-tracker#173]
### Description of the issue

You cannot Linne of Sight once the cast has begun.

Hiding behind a person does work

### Steps To Reproduce

1. player 1: Start the cast of any induction
2. player 2: hides

### Expected Behavior

The induction to go finish

### Where it Happens

anywhere where you can hide behind something

### Entity Information

not applicable

### Screenshots

https://youtu.be/HBIEDXT4W20

**Comment by echoes-emu** [comment]
Fixed

**Comment by sluwe-vos** [comment]
I tried it today on Lore-Master it is still broken. Maybe the patch has yet to go through or it is fixed on the Dev server, so I will hold back to create a second ticket. Thank you for the quick work
